### ISSUE TITLE
Full ChatColor support

### ISSUE THREAD

**Issue by KieronWiltshire** [BlackyPaw/I18N#4]
Add the ability to color the chat correctly. Right now, if you send a message which split's into two lines, only the first line is in color.

**Comment by cieldeville** [comment]
Hello Kieron,

Could you provide me with some material so that I can reproduce the issue?

Best regards,
BlackyPaw.

**Comment by KieronWiltshire** [comment]
Sure, if you'd mind adding me on skype:
kieron.wiltshire

**Comment by cieldeville** [comment]
Fixed in version 0.7.1-SNAPSHOT. Thank you again for pointing this out to me.
